# Stage 1: Build Go Binary
FROM golang:1.24.0-alpine AS builder
WORKDIR /app

# Copy go.mod and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY . .

# Copy .env.dev file to the container
COPY .env.dev .env

# Build the Go application
RUN go build -o main .

# Stage 2: Create a minimal runtime image
FROM alpine:latest
WORKDIR /app

# Copy only the built binary from the builder stage
COPY --from=builder /app/main .

# Expose the required port
EXPOSE 8000

# Set environment variable
ENV PORT=8000 
ENV GO_ENV=Prod
ENV MESSAGE="Lunch in production."
ENV MONGO_URI=mongodb+srv://phuminton:Natsu17102003@gyro.czoey.mongodb.net/
ENV MONGO_DB=GyroDB
ENV MONGO_COLLECTION=data
ENV MONGO_DEVICECOLLECTION=devices
ENV MONGO_USERCOLLECTION=user
ENV MONGO_AUTHCOLLECTION=auth
ENV MQTT_BROKER=mqtt://localhost:1883

# Run the application
CMD ["./main"]
